spring:
  application:
    name: com.nmefc.searchresuce
  #  data:
  #    mongodb:
  #      host: localhost
  #      port: 27017
  #      database: searchrescue
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: searchrescue

server:
  port: 8084